#!/usr/local/php7.1/bin/php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------

$GLOBALS['ENV'] = is_file('ENV') ? trim(file_get_contents('ENV')) : 'LOCAL';

// 定义项目路径
define('APP_PATH', __DIR__ . '/application/');

// 加载框架引导文件
require './thinkphp/console.php';